import type { Metadata } from "next";
import * as api from "../../src/model/api";
import type { GameSpecs } from "@/model/game";
import { StoreRoot } from "@/stores/root";
import "@assets/App.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let hydrationState = undefined;
  try {
    const activeGames: GameSpecs[] = await api.getActiveGames();
    const pendingGames: GameSpecs[] = await api.getPendingGames();
    hydrationState = {
      pending_games: pendingGames ?? [],
      active_games: activeGames ?? [],
    };
  } catch (err) {
    console.error("Failed to fetch initial games", err);
  }

  return (
    <html lang="en">
      <body>
        <StoreRoot hydrationState={hydrationState}>
          <div id="app">{children}</div>
        </StoreRoot>
      </body>
    </html>
  );
}